name: Deploy to Azure App Service via Oryx Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-step4-9
  ORYX_VERSION: 20240510.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Oryx CLI (stable direct GitHub release)
      run: |
        wget https://github.com/microsoft/Oryx/releases/download/20240408.1/oryx_linux_x64.tar.gz
        mkdir oryx
        tar -xzf oryx-linux-x64.tar.gz -C oryx
        sudo mv oryx /opt/oryx
        sudo ln -s /opt/oryx/oryx /usr/local/bin/oryx

    - name: Build with Oryx
      run: |
        oryx build . -o output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./output
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CABE38687E254784A578EFA69B237AA6 }}
